// React/src/Grid.tsx
import { useState, useMemo, useCallback } from 'react';
import DataGrid, {
  Column, RowDragging, Scrolling, Lookup, Selection,
} from 'devextreme-react/data-grid';
import type { DataGridTypes } from 'devextreme-react/data-grid';
import type dxDataGrid from 'devextreme/ui/data_grid';
import type { DragTemplateData } from 'devextreme/ui/draggable';
import CustomStore from 'devextreme/data/custom_store';
import notify from 'devextreme/ui/notify';
import { type Task, priorities } from './data';

type CellValue = Task[keyof Task] | string | undefined;

interface GridDemoComponentProps {
  status?: number;
  tasksStore?: CustomStore;
  shouldClearSelection: boolean;
}

function draggedItemsRender(data: DragTemplateData): JSX.Element {
  const draggedItems = data.itemData.map((item: Task, rowIndex: number) => {
    const cellValues = (Object.keys(item) as (keyof Task)[]).map((key: keyof Task, dataIndex: number) => <td key={`key${dataIndex}`}>{item[key]}</td>);
    return (<tr key={`row${rowIndex}`}>{cellValues}</tr>);
  });
  return (<table className="drag-container">
    <tbody>{draggedItems}</tbody>
  </table>);
}

function getVisibleCellValue(column: DataGridTypes.Column, rowData: Task): CellValue {
  if (column.dataField) {
    const propKey = column.dataField as keyof Task;
    const cellValue = rowData[propKey];
    return column?.lookup?.calculateCellValue
      ? column.lookup.calculateCellValue(cellValue) as CellValue
      : cellValue as CellValue;
  }
  return undefined;
}

function getVisibleRowValues(rowsData: Task[], grid: dxDataGrid): Record<string, CellValue>[] {
  const visibleColumns = grid.getVisibleColumns();
  const selectedData = rowsData.map((rowData: Task) => {
    const visibleValues: Record<string, CellValue> = {};
    visibleColumns.forEach((column: DataGridTypes.Column) => {
      if (column.dataField) { visibleValues[column.dataField] = getVisibleCellValue(column, rowData); }
    });
    return visibleValues;
  });
  return selectedData;
}

export default function Grid({ status, tasksStore, shouldClearSelection }: GridDemoComponentProps): JSX.Element {
  const [updateInProgress, setUpdateInProgress] = useState(false);

  const filterExpr = useMemo(() => ['Status', '=', status], [status]);

  const dataSource = useMemo(() => ({
    store: tasksStore,
    reshapeOnPush: true,
  }), [tasksStore]);

  const canDrag = useCallback((e: DataGridTypes.RowDraggingStartEvent): boolean => {
    if (updateInProgress) return false;
    const visibleRows = e.component.getVisibleRows();
    return visibleRows.some((r: DataGridTypes.Row) => r.isSelected && r.rowIndex === e.fromIndex);
  }, [updateInProgress]);

  const onDragStart = useCallback((e: DataGridTypes.RowDraggingStartEvent): void => {
    const selectedData: Task[] = e.component.getSelectedRowsData();
    e.itemData = getVisibleRowValues(selectedData, e.component);
    e.cancel = !canDrag(e);
  }, [canDrag]);

  const onAdd = useCallback(async (e: DataGridTypes.RowDraggingAddEvent): Promise<void> => {
    const fromGrid = e.fromComponent as dxDataGrid;
    const toGrid = e.toComponent as dxDataGrid;
    const selectedRowKeys: (keyof Task)[] = fromGrid.getSelectedRowKeys();
    const updateProcess: (Promise<any> | undefined)[] = [];
    const changes: any[] = [];

    setUpdateInProgress(true);
    fromGrid.beginCustomLoading('Loading...');
    toGrid.beginCustomLoading('Loading...');
    for (let key of selectedRowKeys) {
      const values = { Status: e.toData };
      updateProcess.push(tasksStore?.update(key, values));
      changes.push({
        type: 'update',
        key,
        data: values,
      });
    }
    try {
      await Promise.all(updateProcess);
      tasksStore?.push(changes);
      fromGrid.endCustomLoading();
      toGrid.endCustomLoading();
      setUpdateInProgress(false);

      fromGrid.clearSelection();
      if (!shouldClearSelection) {
        await toGrid.selectRows(selectedRowKeys, true);
      }
    } catch (error: unknown) {
      notify(error, 'error', 1000);
    }
  }, [tasksStore, shouldClearSelection]);

  return (
    <DataGrid
      dataSource={dataSource}
      height={440}
      showBorders={true}
      filterValue={filterExpr}
    >
      <RowDragging
        data={status}
        group="tasksGroup"
        onAdd={onAdd as unknown as () => void}
        onDragStart={onDragStart as () => void}
        dragRender={draggedItemsRender}
      />
      <Selection mode="multiple" />
      <Scrolling mode="virtual" />
      <Column
        dataField="Subject"
        dataType="string"
      />
      <Column
        dataField="Priority"
        dataType="number"
        width={80}
      >
        <Lookup
          dataSource={priorities}
          valueExpr="id"
          displayExpr="text"
        />
      </Column>
      <Column
        dataField="Status"
        dataType="number"
        visible={false}
      />
    </DataGrid>
  );
}

// Vue/src/components/Grid.vue
<script setup lang="ts">
import DxDataGrid, { DxColumn, DxRowDragging, DxScrolling, DxLookup, DxSelection } from 'devextreme-vue/data-grid';
import type dxDataGrid from 'devextreme/ui/data_grid';
import type { RowDraggingStartEvent, RowDraggingAddEvent, Column, Row } from 'devextreme/ui/data_grid';
import CustomStore from "devextreme/data/custom_store";
import type { Task } from '../data';
import { priorities } from '../data';
import DataSource from "devextreme/data/data_source";

let updateInProgress: Boolean = false;

const props = defineProps({
  tasksStore: CustomStore,
  status: Number,
  shouldClearSelection: Boolean,
});

const filterExpr = ['Status', '=', props.status];

const dataSource = new DataSource({
  store: props.tasksStore,
  reshapeOnPush: true,
});

function getVisibleRowValues(rowsData: Task[], grid: dxDataGrid) {
    const visibleColumns = grid.getVisibleColumns();
    const selectedData = rowsData.map((rowData: Task) => {
        const visibleValues: any = {};
        visibleColumns.forEach((column: Column) => {
            if (column.dataField)
                visibleValues[column.dataField] = getVisibleCellValue(column, rowData);
        });
        return visibleValues;
    });
    return selectedData;
}

function getVisibleCellValue(column: Column, rowData: Task) {
    if (column.dataField) {
        const propKey = column.dataField as (keyof Task);
        const cellValue = rowData[propKey];
        return column.lookup && column.lookup.calculateCellValue ? column.lookup.calculateCellValue(cellValue) : cellValue;
    }
}

function canDrag(e: RowDraggingStartEvent) {
  if (updateInProgress) return false;
  const visibleRows = e.component.getVisibleRows();
  return visibleRows.some((r: Row) => r.isSelected && r.rowIndex === e.fromIndex);
}

function onDragStart(e: RowDraggingStartEvent) {
  const selectedData: Task[] = e.component.getSelectedRowsData();
  e.itemData = getVisibleRowValues(selectedData, e.component);
  e.cancel = !canDrag(e);
}

function onAdd(e: RowDraggingAddEvent) {
  const fromGrid = e.fromComponent as dxDataGrid;
  const toGrid = e.toComponent as dxDataGrid;
  const selectedRowKeys: (keyof Task)[] = fromGrid.getSelectedRowKeys();
  const updateProcess: (Promise<any> | undefined)[] = [];
  const changes: any[] = [];

  updateInProgress = true;
  fromGrid.beginCustomLoading("Loading...");
  toGrid.beginCustomLoading("Loading...");
  for (let key of selectedRowKeys) {
    const values = { Status: e.toData };
    updateProcess.push(props.tasksStore?.update(key, values));
    changes.push({
      type: 'update',
      key,
      data: values,
    });
  }
  Promise.all(updateProcess).then(() => {
    props.tasksStore?.push(changes);
    fromGrid.endCustomLoading();
    toGrid.endCustomLoading();
    updateInProgress = false;

    fromGrid.clearSelection();
    if (!props.shouldClearSelection) {
      toGrid.selectRows(selectedRowKeys, true);
    }
  });
}

</script>
<template>
  <DxDataGrid
    :data-source="dataSource"
    :height="440"
    :show-borders="true"
    :filter-value="filterExpr"
  >
    <DxRowDragging
      :data="status"
      :on-add="onAdd"
      :on-drag-start="onDragStart"
      drag-template="dragItems"
      group="tasksGroup"
    />

    <template #dragItems="{ data }">
      <table className="drag-container">
        <tbody>
          <tr
            v-for="(item, rowIndex) in data.itemData"
            v-bind:key="'row' + rowIndex"
          >
            <td
              v-for="(key, dataIndex) in Object.keys(item)"
              v-bind:key="'key' + dataIndex"
            >
              {{ item[key] }}
            </td>
          </tr>
        </tbody>
      </table>
    </template>

    <DxSelection mode="multiple"/>
    <DxScrolling mode="virtual"/>
    <DxColumn
      data-field="Subject"
      data-type="string"
    />
    <DxColumn
      :width="80"
      data-field="Priority"
      data-type="number"
    >
      <DxLookup
        :data-source="priorities"
        value-expr="id"
        display-expr="text"
      />
    </DxColumn>
    <DxColumn
      :visible="false"
      data-field="Status"
      data-type="number"
    />

  </DxDataGrid>
</template>
