// React/src/App.tsx
import { useCallback, useState } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import * as AspNetData from 'devextreme-aspnet-data-nojquery';
import Grid from './Grid';
import Switch from 'devextreme-react/switch';
import { ValueChangedEvent } from 'devextreme/ui/switch';

const url = 'https://js.devexpress.com/Demos/Mvc/api/DnDBetweenGrids';

const tasksStore = AspNetData.createStore({
  key: 'ID',
  loadUrl: `${url}/Tasks`,
  updateUrl: `${url}/UpdateTask`,
  onBeforeSend(method, ajaxOptions) {
    ajaxOptions.xhrFields = { withCredentials: true };
  },
});

function App() {
  const [shouldClearSelection, setShouldClearSelection] = useState(false);

  const switchValueChanged = useCallback((e: ValueChangedEvent) => {
    setShouldClearSelection(e.value);
  }, []);

  return (
    <div className="demo-container">
        <div className="demo-header">
            <h3>DataGrid - Select multiple items and drag'n'drop between grids</h3>
            <div id="toggle-container">
                <span>Clear selection of dropped items</span>
                <Switch id="clearAfterDropSwitch" value={shouldClearSelection} onValueChanged={switchValueChanged}></Switch>
            </div>
        </div>
        <div className="tables">
          <div className="column">
            <Grid tasksStore={tasksStore} status={1} shouldClearSelection={shouldClearSelection} />
          </div>
          <div className="column">
            <Grid tasksStore={tasksStore} status={2} shouldClearSelection={shouldClearSelection} />
          </div>
      </div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { KeyValue } from '@angular/common';
import { Task, Priority, GridDataService } from 'src/app/services/grid-data.service';
import * as AspNetData from 'devextreme-aspnet-data-nojquery';
import DxDataGrid, {
  RowDraggingStartEvent, RowDraggingAddEvent, Column, Row,
} from 'devextreme/ui/data_grid';
import CustomStore from 'devextreme/data/custom_store';
import { DataSourceOptions } from 'devextreme/data/data_source';
import notify from 'devextreme/ui/notify';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  statuses: number[];

  priorities: Priority[];

  tasksStore: CustomStore;

  dataSource: DataSourceOptions;

  shouldClearSelection = false;

  updateInProgress: Boolean = false;

  constructor(service: GridDataService) {
    const url = 'https://js.devexpress.com/Demos/Mvc/api/DnDBetweenGrids';

    this.priorities = service.getPriorities();
    this.statuses = [1, 2];
    this.tasksStore = AspNetData.createStore({
      key: 'ID',
      loadUrl: `${url}/Tasks`,
      updateUrl: `${url}/UpdateTask`,
      onBeforeSend(method, ajaxOptions) {
        ajaxOptions.xhrFields = { withCredentials: true };
      },
    });
    this.dataSource = {
      store: this.tasksStore,
      reshapeOnPush: true,
    };

    this.onDragStart = this.onDragStart.bind(this);
    this.onAdd = this.onAdd.bind(this);
    this.canDrag = this.canDrag.bind(this);
  }

  onDragStart(e: any): void {
    const selectedData: Task[] = e.component.getSelectedRowsData();
    e.itemData = this.getVisibleRowValues(selectedData, e.component);
    e.cancel = !this.canDrag(e);
  }

  async onAdd(e: any): Promise<void> {
    const fromGrid = e.fromComponent as DxDataGrid;
    const toGrid = e.toComponent as DxDataGrid;
    const selectedRowKeys: (keyof Task)[] = fromGrid.getSelectedRowKeys();
    const updateProcess: Promise<any>[] = [];
    const changes: any[] = [];

    this.updateInProgress = true;
    fromGrid.beginCustomLoading('Loading...');
    toGrid.beginCustomLoading('Loading...');

    for (let key of selectedRowKeys) {
      const values: Task = { Status: e.toData };

      updateProcess.push(this.tasksStore.update(key, values));
      changes.push({
        type: 'update',
        key,
        data: values,
      });
    }

    try {
      await Promise.all(updateProcess);

      this.tasksStore.push(changes);
      fromGrid.endCustomLoading();
      toGrid.endCustomLoading();
      this.updateInProgress = false;

      fromGrid.clearSelection();
      if (!this.shouldClearSelection) {
        await toGrid.selectRows(selectedRowKeys, true);
      }
    } catch {
      notify('An error occurred while saving changes.', 'error', 3000);
    }
  }

  getVisibleRowValues(rowsData: Task[], grid: DxDataGrid): Record<string, Task[keyof Task] | string | undefined>[] {
    const visibleColumns = grid.getVisibleColumns();
    const selectedData = rowsData.map((rowData: Task) => {
      const visibleValues: Record<string, Task[keyof Task] | string | undefined> = {};
      visibleColumns.forEach((column: Column) => {
        if (column.dataField) {
          visibleValues[column.dataField] = this.getVisibleCellValue(column, rowData);
        }
      });
      return visibleValues;
    });
    return selectedData;
  }

  getVisibleCellValue(column: Column, rowData: Task): Task[keyof Task] | string | undefined {
    if (column.dataField) {
      const propKey = column.dataField as keyof Task;
      const cellValue = rowData[propKey];

      return column.lookup?.calculateCellValue
        ? String(column.lookup.calculateCellValue(cellValue))
        : cellValue;
    }
    return undefined;
  }

  canDrag(e: RowDraggingStartEvent): Row | Boolean {
    if (this.updateInProgress) return false;
    const visibleRows = e.component.getVisibleRows();
    return visibleRows.some((r: Row) => r.isSelected && r.rowIndex === e.fromIndex);
  }

  originalOrder(a: KeyValue<number, string>, b: KeyValue<number, string>): number {
    return 0;
  }
}

<div class="default-style">
  <div class="demo-header">
    <h3>DataGrid - Select multiple items and drag'n'drop between grids</h3>
    <div id="toggle-container">
      <span>Clear selection of dropped items</span>
      <dx-switch [(value)]="shouldClearSelection"></dx-switch>
    </div>
  </div>
  <div class="tables">
    <div *ngFor="let status of statuses" class="column">
      <dx-data-grid
        [dataSource]="dataSource"
        [height]="440"
        [showBorders]="true"
        [filterValue]="['Status', '=', status]"
      >
        <dxo-data-grid-row-dragging
          [data]="status"
          group="tasksGroup"
          [onAdd]="onAdd"
          [onDragStart]="onDragStart"
          dragTemplate="drag-template"
        ></dxo-data-grid-row-dragging>

        <div *dxTemplate="let dragData of 'drag-template'">
          <table class="drag-container">
            <tr *ngFor="let rowData of dragData.itemData">
              <td *ngFor="let field of rowData | keyvalue : originalOrder">{{
                field.value
              }}</td>
            </tr>
          </table>
        </div>

        <dxo-selection mode="multiple"></dxo-selection>

        <dxo-scrolling mode="virtual"></dxo-scrolling>

        <dxi-data-grid-column
          dataField="Subject"
          dataType="string"
        ></dxi-data-grid-column>
        <dxi-data-grid-column
          dataField="Priority"
          dataType="number"
          [width]="80"
        >
          <dxo-lookup
            [dataSource]="priorities"
            valueExpr="id"
            displayExpr="text"
          ></dxo-lookup>
        </dxi-data-grid-column>
        <dxi-data-grid-column
          dataField="Status"
          dataType="number"
          [visible]="false"
        ></dxi-data-grid-column>
      </dx-data-grid>
    </div>
  </div>
</div>
